"""Generate spinachlang_ibm_demo.ipynb programmatically."""
import json, pathlib
def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": list(lines)}
def code(*lines):
    return {"cell_type": "code", "execution_count": None,
            "metadata": {}, "outputs": [], "source": list(lines)}
cells = [
# ── Title ─────────────────────────────────────────────────────────────────────
md(
"# SpinachLang × IBM Quantum Simulator Demo\n",
"\n",
"> **SpinachLang** is a quantum programming language that compiles `.sph` source to\n",
"> multiple quantum backends via [PyTKET](https://cqcl.github.io/tket/pytket/api/).\n",
"> This notebook walks the full pipeline:\n",
">\n",
"> ```\n",
"> .sph source\n",
">   ↓  spinachlang.to_tket_circuit()\n",
"> pytket.Circuit  (native TKET IR)\n",
">   ↓  spinachlang.to_qiskit_circuit()  [via pytket-qiskit]\n",
"> qiskit.QuantumCircuit\n",
">   ↓  qiskit_aer.AerSimulator  (IBM Quantum local simulator)\n",
"> Counts / State-vectors / Visualisations\n",
"> ```\n",
"\n",
"---\n",
"\n",
"### Demos in this notebook\n",
"\n",
"| # | Circuit | Key concept |\n",
"|---|---------|-------------|\n",
"| 1 | Single-qubit superposition | Hadamard gate, Bloch sphere |\n",
"| 2 | Bell state (2-qubit entanglement) | CNOT gate, Q-sphere |\n",
"| 3 | GHZ state (3-qubit entanglement) | Multi-qubit correlation |\n",
"| 4 | Deutsch's algorithm | Quantum oracle, phase kickback |\n",
),
# ── Imports ───────────────────────────────────────────────────────────────────
code(
"%matplotlib inline\n",
"import matplotlib.pyplot as plt\n",        # textwrap removed – no longer needed
"import numpy as np\n",
"\n",
"# ── SpinachLang API ───────────────────────────────────────────────────────────\n",
"from spinachlang import to_tket_circuit, to_qiskit_circuit\n",
"\n",
"# ── IBM Quantum / Qiskit ──────────────────────────────────────────────────────\n",
"from qiskit_aer import AerSimulator\n",
"from qiskit.visualization import (\n",
"    plot_histogram,\n",
"    plot_bloch_multivector,\n",
"    plot_state_qsphere,\n",
"    plot_state_city,\n",
")\n",
"from qiskit.quantum_info import Statevector\n",
"\n",
"# ── PyTKET interactive circuit viewer (optional) ──────────────────────────────\n",
"try:\n",
"    from pytket.circuit.display import render_circuit_jupyter\n",
"    _HAS_TKET_DISPLAY = True\n",
"except ImportError:\n",
"    _HAS_TKET_DISPLAY = False\n",
"\n",
"# ── Shared AerSimulator instance ──────────────────────────────────────────────\n",
"simulator = AerSimulator()\n",
"\n",
"\n",
"# ── Helpers ───────────────────────────────────────────────────────────────────\n",
"def show_tket_circuit(tket_circuit):\n",
'    """Render a TKET circuit: interactive HTML when available, text otherwise."""\n',
"    if _HAS_TKET_DISPLAY:\n",
"        return render_circuit_jupyter(tket_circuit)\n",
'    print(f"TKET circuit  ({tket_circuit.n_qubits} qubits, "\n',
'          f"{tket_circuit.n_bits} classical bits, "\n',
'          f"depth {tket_circuit.depth()})")\n',
"    for cmd in tket_circuit.get_commands():\n",
'        print(f"  {cmd}")\n',
"\n",
"\n",
"def run_shots(qiskit_circuit, shots: int = 2048, title: str = \"\"):\n",
'    """Simulate a Qiskit circuit on AerSimulator and plot a histogram."""\n',
"    job    = simulator.run(qiskit_circuit, shots=shots)\n",
"    counts = job.result().get_counts()\n",
"    fig    = plot_histogram(counts,\n",
'                           title=title or "Measurement outcomes",\n',
'                           figsize=(7, 4), color="#4CAF50")\n',
"    plt.tight_layout()\n",
"    return fig, counts\n",
"\n",
"\n",
"def statevector_from(spinach_code: str) -> Statevector:\n",
'    """Return a Qiskit Statevector for Spinach code with NO measurements."""\n',
"    qc = to_qiskit_circuit(spinach_code)\n",
"    return Statevector.from_instruction(qc)\n",
"\n",
"\n",
"import qiskit, qiskit_aer\n",
'print("✅ All imports successful!")\n',
'print(f"   Qiskit      : {qiskit.__version__}")\n',
'print(f"   Qiskit-Aer  : {qiskit_aer.__version__}")\n',
),
# ── Syntax reference ──────────────────────────────────────────────────────────
md(
"## Spinach Language — Quick Reference\n",
"\n",
"```spinach\n",
"# ── Qubit / classical-bit declarations ───────────────────────────────────────\n",
'alice : q 0          # qubit at register index 0  →  Qubit("q", 0)\n',
'flag  : b 0          # classical bit              →  Bit("c", 0)\n',
"\n",
"# ── Apply a gate ──────────────────────────────────────────────────────────────\n",
"alice -> H           # Hadamard on alice\n",
"0     -> H           # shorthand: Hadamard on qubit index 0\n",
"q 0   -> H           # explicit register syntax — same result\n",
"\n",
"# ── Gate pipelines ────────────────────────────────────────────────────────────\n",
"alice -> H | M       # Hadamard then Measure\n",
"\n",
"# ── Two-qubit gates ───────────────────────────────────────────────────────────\n",
"# FCX(arg): acted-on qubit is CONTROL, arg is TARGET\n",
"alice -> H | FCX(q 1)   # Bell pair: alice=control, q[1]=target\n",
"# CX(arg):  arg is CONTROL, acted-on qubit is TARGET\n",
"q 1   -> CX(alice)      # equivalent wiring\n",
"\n",
"# ── Wildcard & list targets ───────────────────────────────────────────────────\n",
"* -> M               # measure ALL qubits\n",
"[alice, q 1] -> H    # apply H to a list\n",
"\n",
"# ── Conditional ───────────────────────────────────────────────────────────────\n",
"q 0 -> X if flag     # classically-conditioned gate\n",
"```\n",
),
# ── Section 1 header ──────────────────────────────────────────────────────────
md(
"---\n",
"## 1  ·  Single-Qubit Superposition\n",
"\n",
"A single Hadamard gate transforms |0⟩ into an equal superposition:\n",
"\n",
"$$|0\\rangle \\xrightarrow{H} \\frac{|0\\rangle + |1\\rangle}{\\sqrt{2}}$$\n",
"\n",
"This is the simplest non-trivial quantum state — the qubit is *simultaneously* 0 and 1\n",
"until observed.  The state sits on the +X equator of the Bloch sphere.\n",
),
# ── Superposition circuit + TKET display ─────────────────────────────────────
code(
"# ── 1a.  Spinach source ───────────────────────────────────────────────────────\n",
'SPH_SUPERPOS      = "0 -> H"       # no measurement  → state-vector\n',
'SPH_SUPERPOS_MEAS = "0 -> H | M"   # with measurement → shot simulation\n',
"\n",
'print("Spinach source (with measurement):")\n',
'print("\\n".join("  " + l for l in SPH_SUPERPOS_MEAS.splitlines()))\n',  # no textwrap
"\n",
"# ── 1b.  PyTKET circuit ───────────────────────────────────────────────────────\n",
"tket_superpos = to_tket_circuit(SPH_SUPERPOS_MEAS)\n",
'print("\\nPyTKET circuit:")\n',
"show_tket_circuit(tket_superpos)\n",
),
# ── Superposition Qiskit diagram ─────────────────────────────────────────────
code(
"# ── 1c.  Qiskit QuantumCircuit diagram ───────────────────────────────────────\n",
"qc_superpos_meas = to_qiskit_circuit(SPH_SUPERPOS_MEAS)\n",
"qc_superpos_meas.draw('mpl', style='iqp', fold=-1)\n",
),
# ── Bloch sphere ─────────────────────────────────────────────────────────────
code(
"# ── 1d.  Bloch sphere — state BEFORE measurement ─────────────────────────────\n",
"# The |+⟩ state sits on the equator of the Bloch sphere at the +X pole.\n",
"sv_superpos = statevector_from(SPH_SUPERPOS)\n",
'print(f"State vector: {sv_superpos.data}")\n',
"\n",
'fig = plot_bloch_multivector(sv_superpos, title="Superposition |+⟩")\n',
"plt.tight_layout()\n",
"plt.show()\n",
),
# ── Superposition shots ───────────────────────────────────────────────────────
code(
"# ── 1e.  Shot simulation — 50/50 histogram ───────────────────────────────────\n",
'fig, counts = run_shots(qc_superpos_meas, shots=2048, title="Superposition: 2048 shots")\n',
"plt.show()\n",
"\n",
'print("Counts:", counts)\n',
"total = sum(counts.values())\n",
"for state, n in sorted(counts.items()):\n",
'    print(f"  |{state}⟩  {n:5d} / {total}  ({100 * n / total:.1f}%)")\n',
),
# ── Section 2 header ──────────────────────────────────────────────────────────
md(
"---\n",
"## 2  ·  Bell State (Two-Qubit Entanglement)\n",
"\n",
"The Bell state $|\\Phi^+\\rangle$ is the archetypal maximally entangled two-qubit state:\n",
"\n",
"$$|\\Phi^+\\rangle = \\frac{|00\\rangle + |11\\rangle}{\\sqrt{2}}$$\n",
"\n",
"**Circuit**: H on qubit 0, then CNOT (q0 = control → q1 = target).  \n",
"In SpinachLang the `FCX` gate acts on the **control** qubit and names the **target** as its argument:\n",
"\n",
"```spinach\n",
"q 0 -> H | FCX(q 1)   # q0 = control, q1 = target\n",
"* -> M\n",
"```\n",
),
# ── Bell circuit + TKET display ───────────────────────────────────────────────
code(
"# ── 2a.  Spinach source ───────────────────────────────────────────────────────\n",
'SPH_BELL      = "q 0 -> H | FCX(q 1)"\n',
'SPH_BELL_MEAS = "q 0 -> H | FCX(q 1)\\n* -> M"\n',
"\n",
'print("Spinach source (with measurement):")\n',
'print("\\n".join("  " + l for l in SPH_BELL_MEAS.splitlines()))\n',  # no textwrap
"\n",
"tket_bell = to_tket_circuit(SPH_BELL_MEAS)\n",
'print("\\nPyTKET circuit:")\n',
"show_tket_circuit(tket_bell)\n",
),
# ── Bell Qiskit diagram ───────────────────────────────────────────────────────
code(
"# ── 2b.  Qiskit QuantumCircuit diagram ───────────────────────────────────────\n",
"qc_bell_meas = to_qiskit_circuit(SPH_BELL_MEAS)\n",
"qc_bell_meas.draw('mpl', style='iqp', fold=-1)\n",
),
# ── Q-sphere ──────────────────────────────────────────────────────────────────
code(
"# ── 2c.  Q-sphere — entangled state before measurement ──────────────────────\n",
"# Equal amplitudes at |00⟩ and |11⟩ (north/south poles of the Q-sphere).\n",
"sv_bell = statevector_from(SPH_BELL)\n",
'print("Non-zero amplitudes:")\n',
'for basis, amp in zip(["00","01","10","11"], sv_bell.data):\n',
"    if abs(amp) > 1e-9:\n",
'        print(f"  |{basis}⟩  amp = {amp:.4f}  prob = {abs(amp)**2:.4f}")\n',
"\n",
'fig = plot_state_qsphere(sv_bell)\n',
'plt.title("Bell state |Φ+⟩")\n',
"plt.show()\n",
),
# ── Bell shots ────────────────────────────────────────────────────────────────
code(
"# ── 2d.  Shot simulation — only |00⟩ and |11⟩ ever appear ──────────────────\n",
'fig, counts = run_shots(qc_bell_meas, shots=2048, title="Bell state |Φ+⟩: 2048 shots")\n',
"plt.show()\n",
'print("Counts:", counts)\n',
"\n",
"# Verify: entanglement means |01⟩ and |10⟩ are forbidden.\n",
'unexpected = {k for k in counts if k not in ("00", "11")}\n',
"if unexpected:\n",
'    print(f"⚠️  Unexpected states: {unexpected}")\n',
"else:\n",
'    print("✅ Only |00⟩ and |11⟩ observed — entanglement confirmed.")\n',
),
# ── Section 3 header ──────────────────────────────────────────────────────────
md(
"---\n",
"## 3  ·  GHZ State (Three-Qubit Entanglement)\n",
"\n",
"The Greenberger–Horne–Zeilinger (GHZ) state generalises the Bell state to three qubits:\n",
"\n",
"$$|\\text{GHZ}\\rangle = \\frac{|000\\rangle + |111\\rangle}{\\sqrt{2}}$$\n",
"\n",
"**Circuit**: H on qubit 0, then chain two CNOTs: 0→1 and 0→2.\n",
"\n",
"```spinach\n",
"q 0 -> H | FCX(q 1) | FCX(q 2)\n",
"* -> M\n",
"```\n",
),
# ── GHZ circuit ───────────────────────────────────────────────────────────────
code(
"# ── 3a.  Spinach source ───────────────────────────────────────────────────────\n",
'SPH_GHZ      = "q 0 -> H | FCX(q 1) | FCX(q 2)"\n',
"SPH_GHZ_MEAS = SPH_GHZ + \"\\n* -> M\"\n",
"\n",
'print("Spinach source:")\n',
'print("\\n".join("  " + l for l in SPH_GHZ_MEAS.splitlines()))\n',  # no textwrap
"\n",
"tket_ghz = to_tket_circuit(SPH_GHZ_MEAS)\n",
'print("\\nPyTKET circuit:")\n',
"show_tket_circuit(tket_ghz)\n",
),
# ── GHZ Qiskit diagram ────────────────────────────────────────────────────────
code(
"# ── 3b.  Qiskit QuantumCircuit diagram ───────────────────────────────────────\n",
"qc_ghz_meas = to_qiskit_circuit(SPH_GHZ_MEAS)\n",
"qc_ghz_meas.draw('mpl', style='iqp', fold=-1)\n",
),
# ── GHZ state-city plot ───────────────────────────────────────────────────────
code(
"# ── 3c.  State-city plot — amplitudes before measurement ─────────────────────\n",
"sv_ghz = statevector_from(SPH_GHZ)\n",
'print("Non-zero amplitudes:")\n',
'basis_labels = [f"{i:03b}" for i in range(8)]\n',
"for label, amp in zip(basis_labels, sv_ghz.data):\n",
"    if abs(amp) > 1e-9:\n",
'        print(f"  |{label}⟩  {amp:.4f}")\n',
"\n",
'fig = plot_state_city(sv_ghz, title="GHZ state amplitudes",\n',
'                     figsize=(8, 5), alpha=0.6,\n',
'                     color=["#4CAF50", "#2196F3"])\n',
"plt.tight_layout()\n",
"plt.show()\n",
),
# ── GHZ shots ─────────────────────────────────────────────────────────────────
code(
"# ── 3d.  Shot simulation — only |000⟩ and |111⟩ ──────────────────────────────\n",
'fig, counts = run_shots(qc_ghz_meas, shots=2048, title="GHZ state: 2048 shots")\n',
"plt.show()\n",
'print("Counts:", counts)\n',
"\n",
'unexpected = {k for k in counts if k not in ("000", "111")}\n',
"if unexpected:\n",
'    print(f"⚠️  Unexpected states: {unexpected}")\n',
"else:\n",
'    print("✅ Only |000⟩ and |111⟩ observed — 3-qubit GHZ entanglement confirmed.")\n',
),
# ── Section 4 header ──────────────────────────────────────────────────────────
md(
"---\n",
"## 4  ·  Deutsch's Algorithm\n",
"\n",
"Deutsch's algorithm decides whether a boolean function $f:\\{0,1\\}\\to\\{0,1\\}$ is\n",
"*constant* (same output for both inputs) or *balanced* (different outputs) using only\n",
"a **single** quantum oracle query — versus two classical queries.\n",
"\n",
"**Measurement result:**\n",
"- Qubit 0 = `0` → $f$ is **constant**  \n",
"- Qubit 0 = `1` → $f$ is **balanced**\n",
"\n",
"The oracle used here implements **f(x) = x** (balanced).\n",
"\n",
"```spinach\n",
"q 1 -> X              # ancilla to |1⟩\n",
"[q 0, q 1] -> H       # superposition on both qubits\n",
"q 1 -> CX(q 0)        # oracle: f(x)=x  — q0 is control, q1 is target\n",
"q 0 -> H | M          # interference + measure\n",
"```\n",
),
# ── Deutsch circuit ───────────────────────────────────────────────────────────
code(
"# ── 4a.  Spinach source ───────────────────────────────────────────────────────\n",
"SPH_DEUTSCH = \"\\n\".join([\n",
'    "# Deutsch\'s algorithm",\n',
'    "q 1 -> X",            # ancilla |1⟩\n',
'    "[q 0, q 1] -> H",     # Hadamard on both\n',
'    "q 1 -> CX(q 0)",      # oracle: f(x) = x  (balanced)\n',
'    "q 0 -> H | M",        # interference + measure\n',
"])\n",
"\n",
'print("Spinach source:")\n',
'print("\\n".join("  " + l for l in SPH_DEUTSCH.splitlines()))\n',  # no textwrap
"\n",
"tket_deutsch = to_tket_circuit(SPH_DEUTSCH)\n",
'print("\\nPyTKET circuit:")\n',
"show_tket_circuit(tket_deutsch)\n",
),
# ── Deutsch Qiskit diagram ────────────────────────────────────────────────────
code(
"# ── 4b.  Qiskit QuantumCircuit diagram ───────────────────────────────────────\n",
"qc_deutsch = to_qiskit_circuit(SPH_DEUTSCH)\n",
"qc_deutsch.draw('mpl', style='iqp', fold=-1)\n",
),
# ── Deutsch shots ─────────────────────────────────────────────────────────────
code(
"# ── 4c.  Shot simulation ─────────────────────────────────────────────────────\n",
'fig, counts = run_shots(qc_deutsch, shots=1024, title="Deutsch\'s algorithm: 1024 shots")\n',
"plt.show()\n",
'print("Counts:", counts)\n',
),
# ── Deutsch interpretation ────────────────────────────────────────────────────
code(
"# ── 4d.  Interpret result ────────────────────────────────────────────────────\n",
"# Qiskit classical-register ordering: rightmost bit = qubit with lowest index.\n",
"# Qubit 0 is the decision qubit; only the last character encodes the answer.\n",
"q0_bits = {state[-1]: n for state, n in counts.items()}\n",
"\n",
"dominant = max(q0_bits, key=q0_bits.get)\n",
'verdict = "BALANCED  (f(0) ≠ f(1))" if dominant == "1" else "CONSTANT  (f(0) = f(1))"\n',
"\n",
'print("Qubit-0 measurement:")\n',
"for bit, n in sorted(q0_bits.items()):\n",
'    bar = "█" * int(40 * n / sum(q0_bits.values()))\n',
'    print(f"  |{bit}⟩  {bar} {n}")\n',
"\n",
'print(f"\\n🔬 Deutsch\'s verdict: function is {verdict}")\n',
'print("   Expected: BALANCED (oracle = f(x) = x)")\n',
'assert dominant == "1", "Deutsch algorithm gave wrong answer!"\n',
'print("✅ Correct.")\n',
),
# ── Summary ───────────────────────────────────────────────────────────────────
md(
"---\n",
"## Summary\n",
"\n",
"This notebook demonstrated SpinachLang's end-to-end pipeline:\n",
"\n",
"1. **Write** compact quantum programs in the Spinach DSL (`.sph` syntax).\n",
"2. **Compile** to a PyTKET `Circuit` with `to_tket_circuit()` — TKET's IR enables\n",
"   backend-agnostic optimisation.\n",
"3. **Convert** to a Qiskit `QuantumCircuit` with `to_qiskit_circuit()` in one call,\n",
"   giving access to the full IBM Quantum ecosystem.\n",
"4. **Simulate** locally with `qiskit_aer.AerSimulator` and visualise with Qiskit's\n",
"   built-in plotting tools.\n",
"\n",
"### Going further\n",
"\n",
"| Goal | Code |\n",
"|------|------|\n",
"| Run on real IBM hardware | `from qiskit_ibm_runtime import QiskitRuntimeService` |\n",
"| Export to OpenQASM 2.0 | `spinachlang.compile_code(sph, \"qasm\")` |\n",
"| Export to Cirq / Quil / Braket | `spinachlang.to_cirq_circuit(sph)` etc. |\n",
"| Noise-model simulation | `AerSimulator.from_backend(noise_model)` |\n",
"| Circuit optimisation | `pytket.passes.FullPeepholeOptimise().apply(tket_circuit)` |\n",
"\n",
"See the [SpinachLang repository](https://github.com/spinachlang/spinachlang) and\n",
"the [PyTKET docs](https://cqcl.github.io/tket/pytket/api/) for more.\n",
),
]
# Assign sequential IDs
for i, cell in enumerate(cells):
    cell["id"] = f"cell-{i:02d}"
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "version": "3.11.0",
        },
    },
    "cells": cells,
}
out = pathlib.Path("/home/cedrick/project/spinachlang/spinachlang-demo/spinachlang_ibm_demo.ipynb")
out.write_text(json.dumps(nb, indent=1, ensure_ascii=False))
print(f"Wrote {out}  ({len(cells)} cells)")
